# Generated by Django 4.2.2 on 2023-06-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='upload',
            field=models.FileField(default=None, upload_to='upload/'),
        ),
    ]
